# http://module-build.sourceforge.net/META-spec-new.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
meta-spec:    1.1
name:         XML-Writer
version:      0.531
abstract:     Easily generate well-formed, namespace-aware XML.
authored_by:
  - David Megginson <david@megginson.com>
  - Ed Avis <ed@membled.com>
  - Joseph Walton <joe@kafsemo.org>
license:      perl
distribution_type: module
installdirs:  site

no_index:
  package:
    - XML::Writer::Namespaces
    - XML::Writer::String

dynamic_config: 0
generated_by: Hand
